from my_library.models.academic_paper_classifier import AcademicPaperClassifier
from my_library.models.bidaf_v import BidafOriginal
from my_library.models.bidaf_v1 import BidafV1
from my_library.models.bidaf_v2 import BidafV2
from my_library.models.bidaf_v3 import BidafV3
from my_library.models.bidaf_v4 import BidafV4
from my_library.models.bidaf_v5 import BidafV5
from my_library.models.bidaf_v6 import BidafV6
from my_library.models.bidaf_v7 import BidafV7
from my_library.models.bidaf_v8 import BidafV8
from my_library.models.bidaf_v9 import BidafV9
